Jacobbrewer1/patcher

- loader.go
- sql.go
- sql_test.go
`LoadDiff` now:
- Takes in a pointer, requiring less validation and making it easier to use
- Says it takes in a struct pointer
- Explains that it will not set zero values
> feat(loader): LoadDiff quality of life improvements

- sql_test.go
- utils.go
Updating method name for handling err no changes
> fix(errors): Updating method name for handling err no changes

- loader.go
- loader_test.go
We are now using the same logic for when checking nil values. Now when we check too see if the the value has been updated, we check the type. This is because the `IsZero()` method returns false which is correct for pointers, however then the `includeZeroValues` flag is true which would then allow the if statement to be true.
> fix(loader): Correcting how we compare for nil values

- .github/workflows/ci-code-approval.yml
- examples/basic_ignores/main.go
- examples/loader_with_opts/main.go
- loader.go
- loader_opts.go
- loader_test.go
Passing the reflected version of the field to the ignore func allowing for users too have more control over the comparisons.
> chore(loader): Changing the ignore funcs signature

- inserter/sql.go
- inserter/sql_test.go
- sql.go
ignoring the pk from the inserter. At this point the ID of the struct will not exist as it is not yet in the database.
> fix(inserter): ignoring the pk from the inserter

- joiner.go
- loader.go
- patch.go
- sql.go
This pull request includes several changes to improve the documentation and functionality of the `SQLPatch` class and related functions. The most important changes involve adding comments to functions and methods to clarify their purpose and usage, as well as minor code adjustments for better readability.
Documentation improvements:
* [`joiner.go`](diffhunk://#diff-cbc3e66aa73ab04bd45680048165e8f32035547825a87bbcad79800c359543caR3): Added a comment to the `Joiner` interface to specify its purpose in generating SQL JOIN clauses.
* [`loader.go`](diffhunk://#diff-322de476adda6446d58b08a7166a7b8fd50b3c060b2f088b44e122c065e3a18eL15-R30): Enhanced the comment for the `LoadDiff` function to better explain its behavior and configuration options.
* …
> feat(comments): Updating comments for methods within the library

- sql.go
- sql_test.go
This pull request includes changes to the `sql.go` and `sql_test.go` files to enhance the `SQLPatch` functionality and improve test coverage. The most important changes include adding support for more data types in the `patchGen` method and introducing a new test to verify this support.
Enhancements to `SQLPatch` functionality:
* [`sql.go`](diffhunk://#diff-76c32ac737291e55d9320a4e63fb5d7d72a97ac34376bab17596e1a4531fd1c6R113-R118): Added support for unsigned integers, floating-point numbers, and complex numbers in the `patchGen` method. [[1]](diffhunk://#diff-76c32ac737291e55d9320a4e63fb5d7d72a97ac34376bab17596e1a4531fd1c6R113-R118) [[2]](diffhunk://#diff-76c32ac737291e55d9320a4e63fb5d7d72a97ac34376bab17596e1a4531fd1c6L121-L122)
Improvements to test coverage:
* …
> fix(gen): adding missing base types to the patch gen method

- .github/workflows/ci-code-approval.yml
This pull request includes changes to the `.github/workflows/ci-code-approval.yml` file to remove the configuration step for private modules. This simplifies the CI workflow by eliminating unnecessary steps.
Simplification of CI workflow:
* [`.github/workflows/ci-code-approval.yml`](diffhunk://#diff-4c8bb8f5cf698728ae107fc054fb2460fb0be2c349f4c5353577be9c6add0c50L41-L45): Removed the "Configure git for private modules" step from multiple job sections. [[1]](diffhunk://#diff-4c8bb8f5cf698728ae107fc054fb2460fb0be2c349f4c5353577be9c6add0c50L41-L45) [[2]](diffhunk://#diff-4c8bb8f5cf698728ae107fc054fb2460fb0be2c349f4c5353577be9c6add0c50L66-L70) [[3]](diffhunk://#diff-4c8bb8f5cf698728ae107fc054fb2460fb0be2c349f4c5353577be9c6add0c50L89-L93)
> chore(cicd): removing setup for private modules as it is not required

- patch_opts.go
- patch_test.go
- sql_test.go
This pull request includes several changes to the `patcher` package, primarily focusing on enhancing the SQL patching functionality and adding comprehensive tests. The most important changes include removing redundant initializations in the `WithWhere` and `WithJoin` functions, adding new test suites and test cases, and improving the handling of different SQL patch scenarios.
Enhancements to SQL patching functionality:
* [`patch_opts.go`](diffhunk://#diff-ca0fec26dd2c06d9588e6e74cdb66b52865144f1d27e76179ab8364dff4ba271L34-L36): Removed redundant initializations of `strings.Builder` in the `WithWhere` and `WithJoin` functions. [[1]](diffhunk://#diff-ca0fec26dd2c06d9588e6e74cdb66b52865144f1d27e76179ab8364dff4ba271L34-L36) [[2]](diffhunk://#diff-ca0fec26dd2c06d9588e6e74cdb66b52865144f1d27e761 …
> chore(tests): Updating tests to cover 80% total

- README.md
This pull request includes a minor update to the `README.md` file. The change corrects the capitalization in the Go Reference badge URL. 
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L3-R3): Updated the Go Reference badge URL to use the correct capitalization for the username in the link.
> fix(docs): Update GO Reference badge on readme

- joiner.go
- wherer.go
This pull request includes changes to the `joiner.go` and `wherer.go` files to improve the robustness of the `appendJoin` and `appendWhere` functions by adding nil checks.
Improvements to function robustness:
* [`joiner.go`](diffhunk://#diff-cbc3e66aa73ab04bd45680048165e8f32035547825a87bbcad79800c359543caR11-R14): Added a nil check for the `Joiner` interface in the `appendJoin` function to prevent potential nil pointer dereferences.
* [`wherer.go`](diffhunk://#diff-4b2cc41829c8fd154e23442cfdb360d0def1a767d947e4995b601d9181ae0256R35-R37): Added a nil check for the `Wherer` interface in the `appendWhere` function to prevent potential nil pointer dereferences.
> fix(opts): Adding check to prevent calls on nil wherer or joiner

- loader.go
- loader_test.go
- patch_opts.go
- sql.go
- sql_test.go
This pull request includes several changes to the `SQLPatch` class and related test cases to improve the handling of ignored fields. The main focus is on ensuring case sensitivity for ignored fields and removing unnecessary string manipulations.
* [`loader.go`](diffhunk://#diff-322de476adda6446d58b08a7166a7b8fd50b3c060b2f088b44e122c065e3a18eL117-R125): Modified the `ignoredFieldsCheck` and `checkIgnoredFields` methods to handle field names without converting them to lowercase.
* [`loader_test.go`](diffhunk://#diff-4c743ecf2cd45e558643f774ff7c6581328a6807bb125951d4feaa5e1954ac26L650-R650): Updated test cases to use case-sensitive field names in the `ignoreFields` list. [[1]](diffhunk://#diff-4c743ecf2cd45e558643f774ff7c6581328a6807bb125951d4feaa5e1954ac26L650-R650) …
> chore(opts): Removing case-insensative ignore field, cases now need to match

- joiner.go
- patch_opts.go
- sql.go
- sql_test.go
- wherer.go
This pull request introduces new functionalities to simplify the creation of SQL statements by adding string-based options for `WHERE` and `JOIN` clauses. Additionally, it includes corresponding tests to ensure the new functionalities work as expected.
* [`joiner.go`](diffhunk://#diff-cbc3e66aa73ab04bd45680048165e8f32035547825a87bbcad79800c359543caR22-R30): Added `joinStringOption` type and `Join` method to support string-based `JOIN` clauses.
* [`patch_opts.go`](diffhunk://#diff-ca0fec26dd2c06d9588e6e74cdb66b52865144f1d27e76179ab8364dff4ba271R37-R71): Added `WithWhereStr` and `WithJoinStr` functions to set `WHERE` and `JOIN` clauses using strings and arguments.
* [`wherer.go`](diffhunk://#diff-4b2cc41829c8fd154e23442cfdb360d0def1a767d947e4995b601d9181ae0256R52-R60): Added …
> feat(opts): Adding with and join string methods

- .github/workflows/ci-code-approval.yml
- mock_MultiFilter.go
- multifilter.go
- multifilter_test.go
- sql_test.go
This pull request includes significant updates to the `MultiFilter` interface and its implementation in the `multifilter.go` file, along with corresponding tests in `multifilter_test.go`. The changes enhance the functionality of the `MultiFilter` by incorporating join operations and updating the `Add` method to handle multiple types of filters.
Enhancements to `MultiFilter`:
* [`multifilter.go`](diffhunk://#diff-3262e86d1549095cd309f6f3b377d0ce864bf5c13ca0ec0bc47a0f213a4179d2R6-R42): Added `Joiner` interface to `MultiFilter` and updated the `Add` method to accept any type of filter, handling both `Joiner` and `Wherer` types.
* [`multifilter.go`](diffhunk://#diff-3262e86d1549095cd309f6f3b377d0ce864bf5c13ca0ec0bc47a0f213a4179d2R6-R42): Implemented `Join` method to return join SQL and …
> feat(multifilter): Adding Joiner interface to the MultiFilter

- .golangci.yaml
- examples/basic_with_opts/main.go
- examples/loader_with_opts/main.go
- inserter/sql.go
- inserter/sql_test.go
- joiner.go
- loader.go
- loader_test.go
- mock_IgnoreFieldsFunc.go
- multifilter.go
- patch.go
- sql.go
- sql_test.go
- wherer.go
This pull request includes several changes to enhance the codebase by improving type safety, updating function signatures, and refining linter configurations. The most important changes are grouped by theme below.
* Updated various function signatures to accept pointers to `reflect.StructField` instead of values to improve type safety and consistency. (`examples/basic_with_opts/main.go`, `examples/loader_with_opts/main.go`, `inserter/sql.go`, `loader.go`, `patch.go`, `mock_IgnoreFieldsFunc.go`) [[1]](diffhunk://#diff-1ca44a8bf1e50aaf6ed31c1c872526e35fbcd27adf61fd4a113a05d83d50bde9L53-R53) [[2]](diffhunk://#diff-dbd94054314c72afb50f3c35a2a1f7830078ce7078ac4871371c62c704c0abc8L56-R56) [[3]](diffhunk://#diff-77861f93deb7ffbdf36c5335d20ea44e2bdd8dce00fd5c70cf2fb2db304a7a6bL65-R65) …
> feat(cicd): Adding additional golangci linters

- inserter/sql.go
- inserter/sql_test.go
- patch.go
- utils.go
This pull request includes several changes to the `inserter/sql.go` file and related test files to improve code readability and functionality. The most important changes include refactoring the `genBatch` and `GenerateSQL` methods, simplifying the `checkSkipField` method, updating test cases, and making the `isValidType` function public.
Improvements to `genBatch` and `GenerateSQL` methods:
* [`inserter/sql.go`](diffhunk://#diff-77861f93deb7ffbdf36c5335d20ea44e2bdd8dce00fd5c70cf2fb2db304a7a6bL15-L103): Refactored the `genBatch` method to simplify the field processing logic and the `GenerateSQL` method to streamline placeholder generation. [[1]](diffhunk://#diff-77861f93deb7ffbdf36c5335d20ea44e2bdd8dce00fd5c70cf2fb2db304a7a6bL15-L103) …
> chore(inserter): Simplifying the inserter package

- loader.go
- loader_test.go
- patch.go
This pull request includes several changes to the `SQLPatch` functionality in `loader.go` and corresponding tests in `loader_test.go`. The most important changes include modifications to the handling of embedded structs, the addition of new test cases, and refactoring of the `shouldSkipField` method.
Improvements to handling embedded structs:
* [`loader.go`](diffhunk://#diff-322de476adda6446d58b08a7166a7b8fd50b3c060b2f088b44e122c065e3a18eL50-R50): Updated the `handleEmbeddedStruct` method to accept an additional `tag` parameter and modified its logic to handle nil values based on the new parameter. [[1]](diffhunk://#diff-322de476adda6446d58b08a7166a7b8fd50b3c060b2f088b44e122c065e3a18eL50-R50) [[2]](diffhunk://#diff-322de476adda6446d58b08a7166a7b8fd50b3c060b2f088b44e122c065e3a18eL84-R93) …
> chore(linters): Updating according to linters

- sql.go
This pull request includes a small but significant change to the `NewDiffSQLPatch` function in the `sql.go` file. The change corrects the logic for comparing fields in the `old` and `newT` structures.
* [`sql.go`](diffhunk://#diff-76c32ac737291e55d9320a4e63fb5d7d72a97ac34376bab17596e1a4531fd1c6L194-R204): Modified the condition to continue the loop when fields in `old` and `newT` are not deeply equal, ensuring that only identical fields are set to zero or nil and added to the ignored fields in the patch.
> chore(sql): Updating acording to linters to reduce nesting

- inserter/batch.go
- inserter/sql.go
This pull request includes several changes to the `inserter` package, focusing on improving the validation logic and refactoring the code for better readability and maintainability. The most important changes include updates to the `validateSQLGen` and `validateSQLInsert` methods, the addition of new helper methods for field checks, and modifications to the `genBatch` and `GenerateSQL` methods.
* [`inserter/batch.go`](diffhunk://#diff-55b1001b6f5d7cd1421e67d9e468962bc8f5fb1fe27aaa2e16b11362e841fcd5L87-R150): Refactored the `validateSQLGen` and `validateSQLInsert` methods to use `switch` statements for better readability and maintainability.
* [`inserter/batch.go`](diffhunk://#diff-55b1001b6f5d7cd1421e67d9e468962bc8f5fb1fe27aaa2e16b11362e841fcd5L87-R150): Added new helper methods …
> chore(inserter): making the inserter package more efficient

- examples/complex_filter/README.md
- examples/complex_filter/main.go
- multifilter.go
This pull request introduces a new example for creating complex filters using the `Joiner` and `Wherer` interfaces and makes several changes to the codebase to support this functionality. The most important changes include the addition of a new example, modifications to existing filter interfaces, and updates to the `patcher` package.
* [`examples/complex_filter/README.md`](diffhunk://#diff-6fbe985d137f3a61a48950e3a0c55e2f7871fe6f70ed410fee4d64fb53f69e46R1-R20): Added a new README file that explains how to use the `Joiner` and `Wherer` interfaces to create a complex filter. This includes a database schema for the `People` and `Contacts` tables.
* [`examples/complex_filter/main.go`](diffhunk://#diff-80ed9cf8337fd5eadf92abc4a52f19c20a9c9bea3db51c3d6dc7890238cbddfaR1-R58): Added a new Go …
> feat(examples): Adding a complex filter example

- inserter/sql.go
- inserter/sql_test.go
This pull request includes changes to the `inserter/sql.go` and `inserter/sql_test.go` files to improve the handling of pointer types and simplify the test assertions. The most important changes include updating the `getFieldValue` method to handle non-nil pointers correctly and replacing `s.Require` assertions with `s` assertions in the test suite.
Improvements to pointer handling:
* [`inserter/sql.go`](diffhunk://#diff-77861f93deb7ffbdf36c5335d20ea44e2bdd8dce00fd5c70cf2fb2db304a7a6bR72-R75): Updated the `getFieldValue` method to handle non-nil pointers by returning the dereferenced value.
Simplification of test assertions:
* [`inserter/sql_test.go`](diffhunk://#diff-d54851d438f801ca655964fe8523e00e7a08b8f1e11efb719b1573e7b6a07345L41-R42): Replaced `s.Require().Len` with `s.Len` in …
> fix(sql): updating the values to not be pointers when added to the args slice

- .golangci.yaml
- inserter/sql_test.go
- loader_test.go
- sql_test.go
This pull request includes updates to the `.golangci.yaml` configuration file and multiple test files to enhance code quality and consistency. The primary changes involve adding a new linter and updating test assertions to use the `require` package for better error handling.
* [`.golangci.yaml`](diffhunk://#diff-9917ddc9f1c3304218f7269265b746d997c5c0615478177b5fceecd33ef47cb5R16): Added `testifylint` to the list of enabled linters and configured it to enable all rules. [[1]](diffhunk://#diff-9917ddc9f1c3304218f7269265b746d997c5c0615478177b5fceecd33ef47cb5R16) [[2]](diffhunk://#diff-9917ddc9f1c3304218f7269265b746d997c5c0615478177b5fceecd33ef47cb5R146-R147)
* [`inserter/sql_test.go`](diffhunk://#diff-d54851d438f801ca655964fe8523e00e7a08b8f1e11efb719b1573e7b6a07345L165-R166): Updated test …
> chore(cicd): updating the cicd to include the testify lint

- .golangci.yaml
This pull request includes a small change to the `.golangci.yaml` file. The change adds a new linter to the list of linters.
* [`.golangci.yaml`](diffhunk://#diff-9917ddc9f1c3304218f7269265b746d997c5c0615478177b5fceecd33ef47cb5R17): Added `perfsprint` to the list of linters.
> feat(cicd): adding perfsprint linter

- .golangci.yaml
This pull request includes a small change to the `.golangci.yaml` file. The change adds `forcetypeassert` to the list of linters.
* [`.golangci.yaml`](diffhunk://#diff-9917ddc9f1c3304218f7269265b746d997c5c0615478177b5fceecd33ef47cb5R18): Added `forcetypeassert` to the list of linters.
> feat(cicd): Type assert linter
