- .github/workflows/ci-code-approval.yml
> fix(cicd): updating the cicd naming

- .clog.toml
> fix(cicd): Updating the clog config

- .clog.toml
> fix(cicd): Removing the trailing .git

- README.md
- examples/basic/basic.go
- examples/joiner/README.md
- examples/joiner/joiner.go
- patch_opts.go
Adding docs on how to use the package
> feat(docs): Adding docs on how to use the package

- sql.go
- sql_test.go
Using a strings builder to build the base of the SQL query
> chore(sql): Using a strings builder to build the base of the SQL query

- patch.go
- sql.go
Updating how the booleans are handled around the sql gen
> chore(gen): Updating how the booleans are handled around the sql gen

- examples/loader/main.go
- loader_test.go
> feat(loader): Adding loader examples

- loader.go
- sql.go
- sql_test.go
Updating the sql gen to user the loader
> feat(loader): Updating the sql gen to user the loader

- examples/loader_sql/main.go
- sql.go
- sql_test.go
Updating the loader sql examples
> chore(examples): Updating the loader sql examples

- .github/workflows/create-release.yml
Changing how we increment the versions
> chore(cicd): Changing how we increment the versions

- pointer.go
- sql_test.go
- utils/point.go
moving ptr utils method to unexported method in package
> fix(utils): moving ptr utils method to unexported method in package

- .clog.toml
Updating the subtitle for the RC
> chore(cicd): Updating the subtitle for the RC

- sql.go
Moving the trimming to use the where type consts
> fix(consts): Moving the trimming to use the where type consts

- sql.go
Adding new method that exports the perform patch for the differ methods
> fix(patcher): Adding new method that exports the perform patch for the differ methods

- sql.go
Correcting logic to perform patching
> fix(perform): Correcting logic to perform patching

- inserter/batch.go
- inserter/batch_opts.go
- inserter/sql.go
- inserter/sql_test.go
- sql.go
Adding a dynamic insert package
> feat(inserter): Adding a dynamic insert package

- loader.go
Updating comment on the loader methods
> chore(loader): Updating comment on the loader methods

- inserter/batch.go
- inserter/batch_opts.go
- inserter/sql.go
- inserter/sql_test.go
updating how resources are passed to keep it consistent
> fix(inserter): updating how resources are passed to keep it consistent

- sql.go
- sql_test.go
- utils.go
returning no changes error when there are no changes
> feat(diffpatcher): returning no changes error when there are no changes

- examples/basic/main.go
- examples/http/main.go
- examples/joiner/main.go
- examples/loader/main.go
- examples/loader_sql/main.go
- examples/where_type/main.go
- go.mod
Updating the module name to be lower case
> chore(deps): Updating the module name to be lower case

- .clog.toml
- README.md
- examples/joiner/README.md
> chore(docs): Updating docs

- examples/loader_with_opts/main.go
- loader_opts.go
Adding example for the loader configuration. Also adding comments around the options to guide users.
This closes #43
> feat(loader): adding example for loader opts

- README.md
updating the load diff example of the readme doc
> chore(docs): updating the load diff example of the readme doc

- loader.go
- loader_test.go
> feat(loader): adding more tests for loader

- loader.go
- loader_test.go
- patch_opts.go
- sql.go
- sql_test.go
Setting this field will configure both the load diff function and the patcher functionality to skip the field.
> feat(config): Adding a struct level tag that will allow users to configure the field to be skipped

- loader.go
- patch.go
- patch_opts.go
- sql.go
refactoring the where variable name to match the join style
> chore(refactore): refactoring the where variable name to match the join style

- sql.go
- sql_test.go
> feat(patch): Updating the patches to use the includes nil and zero

- README.md
- examples/basic/main.go
- examples/basic_with_opts/main.go
- sql.go
- sql_test.go
> feat(examples): Updating examples

- inserter/batch.go
- inserter/batch_opts.go
- inserter/sql.go
- inserter/sql_test.go
- loader.go
- patch.go
- sql.go
Allowing fields to be ignored on the inserter package
> feat(inserter): Allowing fields to be ignored on the inserter package

- README.md
> chore(docs): updating the readme examples

- loader.go
- loader_test.go
- patch.go
- patch_opts.go
- sql.go
- sql_test.go
Adding the ability for users to configure single fields with tag options to allow the field to be nil / zero.
> feat(opts): Allowing singluar field configuration for nillable and zeroable

- inserter/batch.go
- patch.go
- patch_opts.go
initializing on an empty array by default
> chore(inserter): initializing on an empty array by default

- LICENSE
Using Apache Version 2 License
> feat(legal): Using Apache Version 2 License

- loader_test.go
- patch.go
- patch_opts.go
- sql_test.go
swapping tag opts for the omitempty functionality
> feat(omitempty): swapping tag opts for the omitempty functionality

- inserter/batch.go
- inserter/batch_opts.go
- inserter/sql.go
- inserter/sql_test.go
moving the primary key ignore check to the check skip method
> chore(inserter): moving the primary key ignore check

- sql.go
- sql_test.go
Using the first db tag if multiple are provided with the `db` tag
> fix(gen): Using the first db tag if multiple are provided

- utils.go
Adding example to a comment that explains how to use the func
> chore(utils): Adding example to a comment that explains how to use the func

- README.md
adding missing areas to the readme
> chore(docs): adding missing areas to the readme

- CODE_OF_CONDUCT.md
> feat(coc): Create CODE_OF_CONDUCT.md

- inserter/README.md
Adding readme file for the inserter package
> feat(docs): Adding readme file for the inserter package

- inserter/README.md
This pull request includes a small update to the `inserter/README.md` file. The change adds badges for Go Reference and Go Report Card to the README for better visibility of the package's documentation and code quality.
* [`inserter/README.md`](diffhunk://#diff-7f3caba2f1e4979124347cc985ba10fc175e21ef50cc66f3629a97d984c1e02eR3-R5): Added Go Reference and Go Report Card badges to the README.
> chore(docs): Adding relevant external docs for to the readme

- README.md
- inserter/README.md
This pull request includes updates to the `README.md` and `inserter/README.md` files to improve documentation by adding and removing badges.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R3-R6): Added Go Reference and Go Report Card badges to provide quick access to package documentation and code quality reports.
* [`inserter/README.md`](diffhunk://#diff-7f3caba2f1e4979124347cc985ba10fc175e21ef50cc66f3629a97d984c1e02eL3-L5): Removed Go Reference and Go Report Card badges to clean up the documentation.
> fix(docs): moving the labels to the global readme

- README.md
This pull request includes an update to the `README.md` file to add a new section explaining the benefits of using the Patcher library.
Documentation improvements:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R25-R48): Added a new section titled "Why Use Patcher?" which lists the benefits of using the Patcher library, including time-saving, error reduction, code simplification, data synchronization, support for joins, flexible configuration, easy integration, open-source availability, active maintenance, comprehensive documentation, and reliability.
> feat(docs): Adding a section on why to use the library

- .github/workflows/ci-code-approval.yml
This pull request includes an important addition to the CI workflow to ensure code quality by checking code coverage.
Enhancements to CI workflow:
* [`.github/workflows/ci-code-approval.yml`](diffhunk://#diff-4c8bb8f5cf698728ae107fc054fb2460fb0be2c349f4c5353577be9c6add0c50R64-R74): Added a step to check code coverage after running the `make pr-approval` command. This step runs tests, calculates the coverage, and ensures it is at least 80%, failing the build if it is not.
> feat(cicd): Updating cicd to also test for coverage

- patch_opts.go
> fix(opts): Update patch_opts.go comment for casing on ignoring fields

- README.md
This pull request includes a small change to the `README.md` file. The change corrects the formatting for the "Flexible Configuration" feature description by merging two lines into one. 
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L36-R36): Corrected formatting by merging lines for the "Flexible Configuration" feature description.
> fix(docs): updating the fmt on the readme

- CONTRIBUTING.md
This pull request includes a significant update to the `CONTRIBUTING.md` file, providing detailed guidelines for contributing to the project. The most important changes include the addition of sections on getting started, reporting issues, submitting pull requests, code style, commit messages, and reviewing and merging pull requests.
New guidelines added to `CONTRIBUTING.md`:
* Introduction and appreciation for contributors.
* Steps for getting started, including reading the Code of Conduct.
* Detailed instructions on how to report issues and submit pull requests.
* Code style guidelines and formatting requirements.
* Format for clear and concise commit messages.
* Process for reviewing and merging pull requests.
> chore(docs): Create CONTRIBUTING.md

- .golangci.yaml
- sql.go
This pull request includes a small change to the `.golangci.yaml` file. The change adds the `intrange` linter to the list of linters.
* [`.golangci.yaml`](diffhunk://#diff-9917ddc9f1c3304218f7269265b746d997c5c0615478177b5fceecd33ef47cb5R15): Added the `intrange` linter to the `linters` section.
> feat(cicd): adding linter for range loops

- patch.go
- sql.go
This pull request includes minor updates to the `patch.go` and `sql.go` files to improve code readability and maintainability. The changes primarily focus on code formatting and logical flow improvements.
Code readability improvements:
* [`patch.go`](diffhunk://#diff-57f6b83ec3544fa65e2b3e830eb15f5b5bf5f232bd1b488744c56bb303b9f64aL189-R189): Simplified the conditional structure in the `shouldSkipField` method by combining the `if` and `else if` statements for better readability.
Code formatting improvements:
* [`sql.go`](diffhunk://#diff-76c32ac737291e55d9320a4e63fb5d7d72a97ac34376bab17596e1a4531fd1c6L204-L208): Removed unnecessary blank lines in the `NewDiffSQLPatch` function to maintain consistent code formatting.
> chore(repo): refactoring variable names to be more clear
